[project]
name = "travel-planner-with-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "geopy>=2.4.1",
    "google-adk>=0.3.0",
    "google-genai>=1.66.0",
    "python-dotenv>=1.2.2",
    "requests>=2.32.5",
    "streamlit>=1.35.0",
]
